# Pane iframe to access portainer from home assistant
panel_iframe:
  portainer:
    url: https://192.168.1.121:9443
    title: "Portainer"
    icon: mdi:docker
    require_admin: true

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
